name: nix flake check

on:
  push:
  pull_request:

jobs:
  check:
    runs-on: [native-x86_64-linux, bigger-parallel]
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
      - uses: ./.github/actions/setup-home
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          ssh-known-hosts: ${{ vars.SSH_KNOWN_HOSTS }}
          gpg-key-id: ${{ vars.GPG_KEY_ID }}

      - run: nix fmt -L --accept-flake-config -- --ci
      - run: nix flake check -L --accept-flake-config
