name: Setup Git

"on":
  workflow_call:
    outputs:
      git-ssh-command:
        value: ${{ jobs.setup-ssh.outputs.git-ssh-command }}

jobs:
  setup-ssh:
    runs-on: gpg

    outputs:
      git-ssh-command: ${{ steps.ssh.outputs.git-ssh-command }}

    steps:
      - name: Setup SSH
        shell: bash
        run: |
          keyfile="$(mktemp)"
          knownhosts="$(mktemp)"
          config="$(mktemp)"

          printf '%s\n' "$SSH_PRIVATE_KEY" > "$keyfile"
          chmod 600 "$keyfile"

          printf '%s\n' "$SSH_KNOWN_HOSTS" > "$knownhosts"
          chmod 644 "$knownhosts"

          cat > "$config" <<EOF
          Host git.bartoostveen.nl
            IdentityFile "$keyfile"
            User forgejo
            StrictHostKeyChecking yes
            UserKnownHostsFile "$knownhosts"
          EOF
          chmod 600 "$config"

          echo "Trying to connect..."
          ssh -T -F "$config" forgejo@git.bartoostveen.nl

          echo "git-ssh-command=ssh -F $config" >> "$FORGEJO_OUTPUT"
        env:
          SSH_PRIVATE_KEY: "${{ secrets.ssh-private-key }}"
          SSH_KNOWN_HOSTS: "${{ vars.SSH_KNOWN_HOSTS }}"

      - name: import GPG key
        shell: bash
        if: inputs.gpg-key
        run: |
          gpg --import <(cat <<< "${GPG_PRIVKEY:?}")
        env:
          GPG_PRIVKEY: "${{ secrets.gpg-key }}"

      - name: configure git
        shell: bash
        run: |
          git config --global user.name "forgejo-actions[bot]"
          git config --global user.email "git@bartoostveen.nl"
          git config --global push.default simple
          git config --global commit.gpgSign true
          git config --global user.signingKey "${GPG_KEY_ID:?}"
        env:
          GPG_KEY_ID: "${{ vars.GPG_KEY_ID }}"

